trigger:
  branches:
    include:
    - main
  tags:
    include:
    - refs/tags/v*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- script: npm install
  displayName: npm install

- script: |
    sudo npm install -g vsce
    vsce package
  displayName: Create VSIX

- bash: |
    echo ">>> Publish"
    yarn deploy
    displayName: Publish
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'), eq(variables['Agent.OS'], 'Linux'))
  env:
    VSCE_PAT: $(VSCE_PAT)